name: talkjs_flutter
description: Official TalkJS SDK for Flutter
version: 0.8.1
homepage: https://talkjs.com

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.8.1"

platforms:
  android:
  ios:

dependencies:
  flutter:
    sdk: flutter

  talkjs_flutter_inappwebview: ^6.0.7
  crypto: ^3.0.3
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter_local_notifications: ^17.1.0
  http: ^1.2.1
  permission_handler: ^11.3.1
  url_launcher: ^6.2.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2

flutter:
  assets:
    - packages/talkjs_flutter/assets/index.html
